### ISSUE TITLE
New kernel update probably not required

### ISSUE THREAD

**Issue by limed** [mozilla/webprod-jenkins#22]
I am making the assumption that the piece of code to install a newer kernel was required because the initial install of ubuntu (version 14.04) required you to install these extra packages. 

```
    - name: Install a newer kernel
      apt: name=linux-image-{{ kernel }} state=present update_cache=yes cache_valid_time=600
      with_items:
        - "{{ kernel }}"
        - "linux-image-extra-{{ kernel }}"
      register: kernel_installed

    - name: Reboot server
      shell: reboot
when: "kernel_installed|changed"
```

Since technically the docs now says use ubuntu 16.04 I don't think this ansible task is needed
